### ISSUE TITLE
Hardware - Informace k napájení

### ISSUE THREAD

**Issue by kybermonty** [bigclownlabs/doc.bigclown.cz#6]
Mohli byste prosím přidat do dokumentace, jak je to s napájením? Když mám Core modul napájený přes Power modul, je možné propojit Core modul s PC přes USB, aniž by se cokoliv stalo? Na co vlastně slouží piny VDD_OFF a BAT_OFF? U některých desek jsem se setkal s tím, že byly napájené z Li-Ion baterie a po připojení USB se začala tato baterie nabíjet. Umí i Core modul nějaké chytré přepínání napájení? Děkuji za informace.

**Comment by hubpav** [comment]
Ahoj Martine, díky za super podnět.

Právě jsem to zkokumentoval zde: https://doc.bigclown.cz/power-management.html

Budu rád za jakékoliv náměty či dotazy.
P.
